/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e9ddff',
        'primary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#ffb783',
        'on-secondary-fixed': '#23005c',
        'surface-container-highest': '#e5e2e1',
        'on-background': '#1c1b1b',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'primary-container': '#6063ee',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdcc5',
        'inverse-on-surface': '#f3f0ef',
        'tertiary-container': '#b55d00',
        primary: '#4648d4',
        'surface-container-low': '#f6f3f2',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        background: '#fcf9f8',
        'on-tertiary-fixed-variant': '#703700',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-secondary-container': '#fffbff',
        'on-primary-fixed-variant': '#2f2ebe',
        outline: '#767586',
        'surface-bright': '#fcf9f8',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        secondary: '#6b38d4',
        'secondary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#301400',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#fffbff',
        surface: '#fcf9f8',
        'on-error': '#ffffff',
        'secondary-container': '#8455ef',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        tertiary: '#904900',
        'surface-tint': '#494bd6',
        'outline-variant': '#c7c4d7',
        'surface-dim': '#dcd9d9',
        'inverse-primary': '#c0c1ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#5516be',
        'inverse-surface': '#313030',
        'on-surface-variant': '#464554',
        'on-secondary': '#ffffff',
        // Custom dark-mode palette — the Material-export tokens above are a
        // light scheme only (no real dark surface exists in them), so a
        // dedicated dark palette is defined here for the `dark:` variant.
        'night-bg': '#121016',
        'night-surface': '#1b1922',
        'night-surface-2': '#242230',
        'night-surface-3': '#2e2b3a',
        'night-border': '#332f42',
        'night-text': '#f1eef5',
        'night-muted': '#a9a5b8',
        'night-primary': '#c0c1ff',
        'night-on-primary': '#1b1a52',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '20px',
        'margin-desktop': '40px',
        sm: '8px',
        base: '4px',
        md: '16px',
        xl: '32px',
        xs: '4px',
        'container-max': '1440px',
        '2xl': '48px',
        'margin-mobile': '16px',
        '3xl': '64px',
        lg: '24px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Hanken Grotesk'],
        'label-sm': ['Hanken Grotesk'],
        'display-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'label-sm-mobile': ['11px', { lineHeight: '1.0', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      keyframes: {
        riseIn: {
          '0%': { opacity: '0', transform: 'translateY(18px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        popIn: {
          '0%': { opacity: '0', transform: 'scale(0.88)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '50%': { transform: 'translate(14px, -22px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-400px 0' },
          '100%': { backgroundPosition: '400px 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        skeletonPulse: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
      animation: {
        'rise-in': 'riseIn 0.6s cubic-bezier(0.22, 1, 0.36, 1) both',
        'pop-in': 'popIn 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        shimmer: 'shimmer 1.6s ease-in-out infinite',
        'fade-in': 'fadeIn 0.3s ease both',
        'skeleton-pulse': 'skeletonPulse 1.8s ease-in-out infinite',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
